#############################################################################
# Makefile for building: libqtflickr.so.0.1.0
# Generated by qmake (2.01a) (Qt 4.6.0) on: Tue Mar 30 09:11:10 2010
# Project:  qtflickr.pro
# Template: lib
# Command: /opt/qtsdk-2009.05/qt/bin/qmake -spec /opt/qtsdk-2009.05/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile qtflickr.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I/opt/qtsdk-2009.05/qt/mkspecs/linux-g++ -I. -I/opt/qtsdk-2009.05/qt/include/QtCore -I/opt/qtsdk-2009.05/qt/include/QtNetwork -I/opt/qtsdk-2009.05/qt/include/QtGui -I/opt/qtsdk-2009.05/qt/include/QtXml -I/opt/qtsdk-2009.05/qt/include -Ibuilddir
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/qtsdk-2009.05/qt/lib -shared -Wl,-soname,libqtflickr.so.0
LIBS          = $(SUBLIBS)  -L/opt/qtsdk-2009.05/qt/lib -lQtXml -L/opt/qtsdk-2009.05/qt/lib -lQtGui -L/usr/X11R6/lib -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qtsdk-2009.05/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = builddir/

####### Files

SOURCES       = qtflickr.cpp \
		qtflickr_p.cpp builddir/moc_qtflickr.cpp \
		builddir/moc_qtflickr_p.cpp
OBJECTS       = builddir/qtflickr.o \
		builddir/qtflickr_p.o \
		builddir/moc_qtflickr.o \
		builddir/moc_qtflickr_p.o
DIST          = /opt/qtsdk-2009.05/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/shared.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/dll.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf \
		qtflickr.pro
QMAKE_TARGET  = qtflickr
DESTDIR       = lib/
TARGET        = libqtflickr.so.0.1.0
TARGETA       = lib/libqtflickr.a
TARGETD       = libqtflickr.so.0.1.0
TARGET0       = libqtflickr.so
TARGET1       = libqtflickr.so.0
TARGET2       = libqtflickr.so.0.1

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  lib/$(TARGET)

lib/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@$(CHK_DIR_EXISTS) lib/ || $(MKDIR) lib/ 
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	-$(DEL_FILE) lib/$(TARGET)
	-$(DEL_FILE) lib/$(TARGET0)
	-$(DEL_FILE) lib/$(TARGET1)
	-$(DEL_FILE) lib/$(TARGET2)
	-$(MOVE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2) lib/



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: qtflickr.pro  /opt/qtsdk-2009.05/qt/mkspecs/linux-g++/qmake.conf /opt/qtsdk-2009.05/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/shared.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/dll.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf \
		/opt/qtsdk-2009.05/qt/lib/libQtXml.prl \
		/opt/qtsdk-2009.05/qt/lib/libQtCore.prl \
		/opt/qtsdk-2009.05/qt/lib/libQtGui.prl \
		/opt/qtsdk-2009.05/qt/lib/libQtNetwork.prl
	$(QMAKE) -spec /opt/qtsdk-2009.05/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile qtflickr.pro
/opt/qtsdk-2009.05/qt/mkspecs/common/g++.conf:
/opt/qtsdk-2009.05/qt/mkspecs/common/unix.conf:
/opt/qtsdk-2009.05/qt/mkspecs/common/linux.conf:
/opt/qtsdk-2009.05/qt/mkspecs/qconfig.pri:
/opt/qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/qt_config.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/default_pre.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/debug.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/default_post.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/shared.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/dll.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/warn_on.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/qt.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/moc.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/resources.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/uic.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/yacc.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/lex.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf:
/opt/qtsdk-2009.05/qt/lib/libQtXml.prl:
/opt/qtsdk-2009.05/qt/lib/libQtCore.prl:
/opt/qtsdk-2009.05/qt/lib/libQtGui.prl:
/opt/qtsdk-2009.05/qt/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qtsdk-2009.05/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile qtflickr.pro

dist: 
	@$(CHK_DIR_EXISTS) builddir/qtflickr0.1.0 || $(MKDIR) builddir/qtflickr0.1.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) builddir/qtflickr0.1.0/ && $(COPY_FILE) --parents qtflickr.h qtflickr_p.h builddir/qtflickr0.1.0/ && $(COPY_FILE) --parents qtflickr.cpp qtflickr_p.cpp builddir/qtflickr0.1.0/ && (cd `dirname builddir/qtflickr0.1.0` && $(TAR) qtflickr0.1.0.tar qtflickr0.1.0 && $(COMPRESS) qtflickr0.1.0.tar) && $(MOVE) `dirname builddir/qtflickr0.1.0`/qtflickr0.1.0.tar.gz . && $(DEL_FILE) -r builddir/qtflickr0.1.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) lib/$(TARGET) 
	-$(DEL_FILE) lib/$(TARGET0) lib/$(TARGET1) lib/$(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: builddir/moc_qtflickr.cpp builddir/moc_qtflickr_p.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) builddir/moc_qtflickr.cpp builddir/moc_qtflickr_p.cpp
builddir/moc_qtflickr.cpp: qtflickr.h
	/opt/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) qtflickr.h -o builddir/moc_qtflickr.cpp

builddir/moc_qtflickr_p.cpp: qtflickr.h \
		qtflickr_p.h
	/opt/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) qtflickr_p.h -o builddir/moc_qtflickr_p.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

builddir/qtflickr.o: qtflickr.cpp qtflickr.h \
		qtflickr_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o builddir/qtflickr.o qtflickr.cpp

builddir/qtflickr_p.o: qtflickr_p.cpp qtflickr_p.h \
		qtflickr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o builddir/qtflickr_p.o qtflickr_p.cpp

builddir/moc_qtflickr.o: builddir/moc_qtflickr.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o builddir/moc_qtflickr.o builddir/moc_qtflickr.cpp

builddir/moc_qtflickr_p.o: builddir/moc_qtflickr_p.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o builddir/moc_qtflickr_p.o builddir/moc_qtflickr_p.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

