# #####################################################################
# Automatically generated by qmake (2.01a) Tue Aug 11 09:37:41 2009
# #####################################################################
CONFIG += static \
    shared
VERSION = 0.1.0
QT += network \
    xml
TEMPLATE = lib
TARGET = qtflickr
DESTDIR = ./lib
OBJECTS_DIR = ./builddir
MOC_DIR = ./builddir
RCC_DIR = ./builddir

# Input
HEADERS += qtflickr.h \
    qtflickr_p.h
SOURCES += qtflickr.cpp \
    qtflickr_p.cpp
